#!/bin/sh
# Installer for agy-acp (effort-split fork).
# Builds the release binary and installs it plus the T3 wrapper to $PREFIX/bin.
#
# Usage:
#   ./install.sh                 # installs to ~/.local/bin
#   PREFIX=/usr/local ./install.sh
#
# Requirements: cargo (rust 1.70+), agy CLI installed and authenticated.

set -eu

PREFIX="${PREFIX:-$HOME/.local}"
BINDIR="$PREFIX/bin"
SCRIPT_DIR="$(CDPATH= cd -- "$(dirname -- "$0")" && pwd)"

fail() { echo "error: $*" >&2; exit 1; }

command -v cargo >/dev/null 2>&1 || fail "cargo not found (install rust 1.70+ first)"
command -v agy >/dev/null 2>&1 || fail "agy CLI not found in PATH (install + login first)"

echo "building release binary..."
cargo build --release --manifest-path "$SCRIPT_DIR/Cargo.toml"

mkdir -p "$BINDIR"
install -m755 "$SCRIPT_DIR/target/release/agy-acp" "$BINDIR/agy-acp"

# Wrapper for T3 Code's "Executable override": T3 appends the registry's
# arguments (e.g. --uid= on linux) which plain agy-acp rejects, so strip them
# here. Also guarantees `agy` is on PATH and enables auto-approve, because
# interactive permission prompts cannot be answered over ACP.
cat > "$BINDIR/agy-acp-t3" <<EOF
#!/bin/sh
# Generated by agy-acp install.sh. Do not edit by hand (re-runs overwrite it).
export PATH="$BINDIR:\$HOME/.local/bin:\$PATH"
export AGY_EXTRA_ARGS="\${AGY_EXTRA_ARGS:---dangerously-skip-permissions}"
# Drop T3's registry flags (--uid=) while preserving every other arg exactly
# (rotation idiom: no eval, safe for spaces/quotes/\$).
total=\$#
i=0
while [ \$i -lt \$total ]; do
  case "\$1" in
    --uid*) shift ;;
    *) arg="\$1"; shift; set -- "\$@" "\$arg" ;;
  esac
  i=\$((i + 1))
done
exec "$BINDIR/agy-acp" "\$@"
EOF
chmod 755 "$BINDIR/agy-acp-t3"

echo
echo "installed:"
echo "  $BINDIR/agy-acp      (ACP adapter)"
echo "  $BINDIR/agy-acp-t3   (T3 wrapper)"
echo
echo "T3 Code setup: Settings > Providers > Add provider > Enter manually"
echo "  Registry agent ID:    antigravity-acp"
echo "  Executable override:  $BINDIR/agy-acp-t3"
echo "  Authentication:       auto (uses your existing 'agy' login)"
